services:
  master: # user-facing container, with NodeJS and VSCode Server
    image: master:latest
    ports:
      - "9000:3000"
    volumes:
       - ../csc418lec:/lectures # csc418lec is a github repo (could be private or public) containing lecture materials
       - ../csc418data:/data # csc418data is a github repo (could be private or public) containing relevant data and example codes
    depends_on: 
      - worker
    
  worker: # back-end MongoDB container
    image: worker:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=goldenrams
    ports:
      - "27017:27017"
    volumes:
       - mongo-data:/data/db
       
networks:
  default:
    driver: bridge

